# Site wide configuration

title:            tombola
locale:           en_UK
url:              

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Tom Readings
  avatar: bio-photo.jpg
  bio: "Technologist, Developer, Geek"
  email: 
  disqus-shortname: autopoietic
  twitter: tomreadings #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-47938601-1
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: tombola #username
  drupal: autopoietic
  stackoverflow: #http://stackoverflow.com/users/123456/username
  drupalanswers: 19551
  medium: tomreadings #username
  linkedin: # treadings #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
